apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:panupongdeve/nonprod-k8s-manifests.git
    targetRevision: develop
    path: dev/e-commerce/cart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

