apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:panupongdeve/nonprod-k8s-manifests.git
    targetRevision: develop
    path: dev/e-commerce/

  destination:
    server: https://kubernetes.default.svc
    namespace: cart-dev

