apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: cart-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - image: 164b51b
          name: cart
          ports:
            - containerPort: 9000
