apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: cart-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - image: panupongdeve/gitops-my-cart:v1
        name: cart
        ports:
        - containerPort: 9000
