apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cart
  namespace: cart-dev
  envs: 
  - ./cart/cart.env

# Generator Option
generatorOptions:
  disableNameSuffixHash: true